version: "3.6"

services:
  eosio-node:
    hostname: eosio-node
    image: fsword/eosnode
    volumes:
      - ./config/eosio-node/config.ini:/opt/eosio/config.ini.template:ro
      - ./config/genesis.json:/opt/eosio/genesis.json:ro
  eosio-bp1-node:
    hostname: eosio-bp1-node
    image: fsword/eosnode
    volumes:
      - ./config/eosio-bp1-node/config.ini:/opt/eosio/config.ini.template:ro
      - ./config/genesis.json:/opt/eosio/genesis.json:ro

  eosio-bp2-node:
    hostname: eosio-bp2-node
    image: fsword/eosnode
    volumes:
      - ./config/eosio-bp2-node/config.ini:/opt/eosio/config.ini.template:ro
      - ./config/genesis.json:/opt/eosio/genesis.json:ro

  keosd:
    image: fsword/eosnode
    working_dir: /opt/contracts
    entrypoint: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900
    volumes:
      - ./contracts:/opt/contracts


