version: "3"

services:
  eosio-node:
    hostname: eosio-node
    image: fsword/eosnode
    volumes:
      - ./eosio-node/config.ini:/opt/eosio/bin/data-dir/config.ini.template:ro
      - ./genesis.json:/opt/eosio/bin/data-dir/genesis.json:ro
  eosio-bp1-node:
    hostname: eosio-bp1-node
    image: fsword/eosnode
    volumes:
      - ./eosio-bp1-node/config.ini:/opt/eosio/bin/data-dir/config.ini.template:ro
      - ./genesis.json:/opt/eosio/bin/data-dir/genesis.json:ro

  eosio-bp2-node:
    hostname: eosio-bp2-node
    image: fsword/eosnode
    volumes:
      - ./eosio-bp2-node/config.ini:/opt/eosio/bin/data-dir/config.ini.template:ro
      - ./genesis.json:/opt/eosio/bin/data-dir/genesis.json:ro

  keosd:
    image: eosio/eos:v1.0.7
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900

